[package]
name = "silicon"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
silicon-hal = { path = "../silicon-hal" }
embedded-hal = "1"
embedded-hal-bus = "0.3.0"
embedded-sdmmc = { version = "0.9.0", default-features = false, features = [] }

[profile.dev]
panic = "abort"
strip = true
opt-level = "s"

[profile.release]
panic = "abort"
strip = true
opt-level = "s"
