[unstable]
build-std = ["core"]

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tmemory.x",     # memory.x must appear BEFORE link.x
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-args=--gc-sections",
    "-Z",
    "no-unique-section-names",
    "-Z",
    "location-detail=none",
    "-Z",
    "fmt-debug=none",
]
runner = "scripts/post_build.sh"
