[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tmemory.x",     # memory.x must appear BEFORE link.x
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-args=--gc-sections",
    "-Z",
    "no-unique-section-names",
]
runner = "scripts/post_build.sh"

[target.riscv32i-unknown-none-elf.unstable]
build-std = "core"